export const USER_CREATING = 'USER_CREATING';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_ERROR = 'USER_CREATE_ERROR';
export const RESET_USER_CREATE = 'RESET_USER_CREATE';

export const USER_UPDATING = 'USER_UPDATING';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';
export const RESET_USER_UPDATE = 'RESET_USER_UPDATE';

export const USER_DELETING = 'USER_DELETING';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_ERROR = 'USER_DELETE_ERROR';
export const RESET_USER_DELETE = 'RESET_USER_DELETE';

export const USER_REQUESTING = 'USER_REQUESTING';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';
export const USER_REQUEST_ERROR = 'USER_REQUEST_ERROR';
export const RESET_USER_REQUEST = 'RESET_USER_REQUEST';

export const USERS_REQUESTING = 'USERS_REQUESTING';
export const USERS_REQUEST_SUCCESS = 'USERS_REQUEST_SUCCESS';
export const USERS_REQUEST_ERROR = 'USERS_REQUEST_ERROR';
export const RESET_USERS_REQUEST = 'RESET_USERS_REQUEST';
