export const ALBUM_CREATING = 'ALBUM_CREATING';
export const ALBUM_CREATE_SUCCESS = 'ALBUM_CREATE_SUCCESS';
export const ALBUM_CREATE_ERROR = 'ALBUM_CREATE_ERROR';
export const RESET_ALBUM_CREATE = 'RESET_ALBUM_CREATE';

export const ALBUM_UPDATING = 'ALBUM_UPDATING';
export const ALBUM_UPDATE_SUCCESS = 'ALBUM_UPDATE_SUCCESS';
export const ALBUM_UPDATE_ERROR = 'ALBUM_UPDATE_ERROR';
export const RESET_ALBUM_UPDATE = 'RESET_ALBUM_UPDATE';

export const ALBUM_DELETING = 'ALBUM_DELETING';
export const ALBUM_DELETE_SUCCESS = 'ALBUM_DELETE_SUCCESS';
export const ALBUM_DELETE_ERROR = 'ALBUM_DELETE_ERROR';
export const RESET_ALBUM_DELETE = 'RESET_ALBUM_DELETE';

export const ALBUM_REQUESTING = 'ALBUM_REQUESTING';
export const ALBUM_REQUEST_SUCCESS = 'ALBUM_REQUEST_SUCCESS';
export const ALBUM_REQUEST_ERROR = 'ALBUM_REQUEST_ERROR';
export const RESET_ALBUM_REQUEST = 'RESET_ALBUM_REQUEST';

export const ALBUMS_REQUESTING = 'ALBUMS_REQUESTING';
export const ALBUMS_REQUEST_SUCCESS = 'ALBUMS_REQUEST_SUCCESS';
export const ALBUMS_REQUEST_ERROR = 'ALBUMS_REQUEST_ERROR';
export const RESET_ALBUMS_REQUEST = 'RESET_ALBUMS_REQUEST';
