export const PHOTO_CREATING = 'PHOTO_CREATING';
export const PHOTO_CREATE_SUCCESS = 'PHOTO_CREATE_SUCCESS';
export const PHOTO_CREATE_ERROR = 'PHOTO_CREATE_ERROR';
export const RESET_PHOTO_CREATE = 'RESET_PHOTO_CREATE';

export const PHOTO_UPDATING = 'PHOTO_UPDATING';
export const PHOTO_UPDATE_SUCCESS = 'PHOTO_UPDATE_SUCCESS';
export const PHOTO_UPDATE_ERROR = 'PHOTO_UPDATE_ERROR';
export const RESET_PHOTO_UPDATE = 'RESET_PHOTO_UPDATE';

export const PHOTO_DELETING = 'PHOTO_DELETING';
export const PHOTO_DELETE_SUCCESS = 'PHOTO_DELETE_SUCCESS';
export const PHOTO_DELETE_ERROR = 'PHOTO_DELETE_ERROR';
export const RESET_PHOTO_DELETE = 'RESET_PHOTO_DELETE';

export const PHOTO_REQUESTING = 'PHOTO_REQUESTING';
export const PHOTO_REQUEST_SUCCESS = 'PHOTO_REQUEST_SUCCESS';
export const PHOTO_REQUEST_ERROR = 'PHOTO_REQUEST_ERROR';
export const RESET_PHOTO_REQUEST = 'RESET_PHOTO_REQUEST';

export const PHOTOS_REQUESTING = 'PHOTOS_REQUESTING';
export const PHOTOS_REQUEST_SUCCESS = 'PHOTOS_REQUEST_SUCCESS';
export const PHOTOS_REQUEST_ERROR = 'PHOTOS_REQUEST_ERROR';
export const RESET_PHOTOS_REQUEST = 'RESET_PHOTOS_REQUEST';
