export const POST_CREATING = 'POST_CREATING';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_ERROR = 'POST_CREATE_ERROR';
export const RESET_POST_CREATE = 'RESET_POST_CREATE';

export const POST_UPDATING = 'POST_UPDATING';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_ERROR = 'POST_UPDATE_ERROR';
export const RESET_POST_UPDATE = 'RESET_POST_UPDATE';

export const POST_DELETING = 'POST_DELETING';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_ERROR = 'POST_DELETE_ERROR';
export const RESET_POST_DELETE = 'RESET_POST_DELETE';

export const POST_REQUESTING = 'POST_REQUESTING';
export const POST_REQUEST_SUCCESS = 'POST_REQUEST_SUCCESS';
export const POST_REQUEST_ERROR = 'POST_REQUEST_ERROR';
export const RESET_POST_REQUEST = 'RESET_POST_REQUEST';

export const POSTS_REQUESTING = 'POSTS_REQUESTING';
export const POSTS_REQUEST_SUCCESS = 'POSTS_REQUEST_SUCCESS';
export const POSTS_REQUEST_ERROR = 'POSTS_REQUEST_ERROR';
export const RESET_POSTS_REQUEST = 'RESET_POSTS_REQUEST';
