/* Get access token */
export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_ERROR = 'LOGIN_REQUEST_ERROR';
export const RESET_LOGIN_REQUEST = 'RESET_LOGIN_REQUEST';

export const INIT_URL = 'INIT_URL';

/* Refresh access token */
export const REFRESH_TOKEN_REQUESTING = 'REFRESH_TOKEN_REQUESTING';
export const REFRESH_TOKEN_REQUEST_SUCCESS = 'REFRESH_TOKEN_REQUEST_SUCCESS';
export const REFRESH_TOKEN_REQUEST_ERROR = 'REFRESH_TOKEN_REQUEST_ERROR';
export const RESET_REFRESH_TOKEN_REQUEST = 'RESET_REFRESH_TOKEN_REQUEST';

/* Revoke access token */
export const REVOKE_TOKEN_REQUESTING = 'REVOKE_TOKEN_REQUESTING';
export const REVOKE_TOKEN_REQUEST_SUCCESS = 'REVOKE_TOKEN_REQUEST_SUCCESS';
export const REVOKE_TOKEN_REQUEST_ERROR = 'REVOKE_TOKEN_REQUEST_ERROR';
export const RESET_REVOKE_TOKEN_REQUEST = 'RESET_REVOKE_TOKEN_REQUEST';

/* Sign out user */
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
