export const COMMENT_CREATING = 'COMMENT_CREATING';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';
export const COMMENT_CREATE_ERROR = 'COMMENT_CREATE_ERROR';
export const RESET_COMMENT_CREATE = 'RESET_COMMENT_CREATE';

export const COMMENT_UPDATING = 'COMMENT_UPDATING';
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS';
export const COMMENT_UPDATE_ERROR = 'COMMENT_UPDATE_ERROR';
export const RESET_COMMENT_UPDATE = 'RESET_COMMENT_UPDATE';

export const COMMENT_DELETING = 'COMMENT_DELETING';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_ERROR = 'COMMENT_DELETE_ERROR';
export const RESET_COMMENT_DELETE = 'RESET_COMMENT_DELETE';

export const COMMENT_REQUESTING = 'COMMENT_REQUESTING';
export const COMMENT_REQUEST_SUCCESS = 'COMMENT_REQUEST_SUCCESS';
export const COMMENT_REQUEST_ERROR = 'COMMENT_REQUEST_ERROR';
export const RESET_COMMENT_REQUEST = 'RESET_COMMENT_REQUEST';

export const COMMENTS_REQUESTING = 'COMMENTS_REQUESTING';
export const COMMENTS_REQUEST_SUCCESS = 'COMMENTS_REQUEST_SUCCESS';
export const COMMENTS_REQUEST_ERROR = 'COMMENTS_REQUEST_ERROR';
export const RESET_COMMENTS_REQUEST = 'RESET_COMMENTS_REQUEST';
