export const TODO_CREATING = 'TODO_CREATING';
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS';
export const TODO_CREATE_ERROR = 'TODO_CREATE_ERROR';
export const RESET_TODO_CREATE = 'RESET_TODO_CREATE';

export const TODO_UPDATING = 'TODO_UPDATING';
export const TODO_UPDATE_SUCCESS = 'TODO_UPDATE_SUCCESS';
export const TODO_UPDATE_ERROR = 'TODO_UPDATE_ERROR';
export const RESET_TODO_UPDATE = 'RESET_TODO_UPDATE';

export const TODO_DELETING = 'TODO_DELETING';
export const TODO_DELETE_SUCCESS = 'TODO_DELETE_SUCCESS';
export const TODO_DELETE_ERROR = 'TODO_DELETE_ERROR';
export const RESET_TODO_DELETE = 'RESET_TODO_DELETE';

export const TODO_REQUESTING = 'TODO_REQUESTING';
export const TODO_REQUEST_SUCCESS = 'TODO_REQUEST_SUCCESS';
export const TODO_REQUEST_ERROR = 'TODO_REQUEST_ERROR';
export const RESET_TODO_REQUEST = 'RESET_TODO_REQUEST';

export const TODOS_REQUESTING = 'TODOS_REQUESTING';
export const TODOS_REQUEST_SUCCESS = 'TODOS_REQUEST_SUCCESS';
export const TODOS_REQUEST_ERROR = 'TODOS_REQUEST_ERROR';
export const RESET_TODOS_REQUEST = 'RESET_TODOS_REQUEST';
